# local config is being used for running component locally for testing and debugging purposes

server:
  apiVersion: v1
  address: ":8443"
  readTimeout: 10s
  writeTimeout: 10s 
  privateKey: test/cert/server.key
  certificate: test/cert/server.pub
  insecure: true

logger:
  level: debug
  addCaller: true
  outputPaths:
    - stdout

database:
  DSN: "/tmp/models_test.db"
  dialect: "sqlite3"

geoip:
  useGeoIP: true
  dbFileName: fixtures/GeoLite2-Country_20221202/GeoLite2-Country.mmdb
